# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pluk', '0019_auto_20170113_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pluk.Article'),
        ),
        migrations.AlterField(
            model_name='userlikes',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pluk.Article', verbose_name='Статья'),
        ),
    ]
